apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms400-deployment
  namespace: ms400-namespace
  annotations:
    kubernetes.io/change-cause: "Initial Deploy"
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ms400-pod
  template:
    metadata:
      labels:
        app: ms400-pod
    spec:
      containers:
        - name: ms400-container
          image: gmahechas/ms400-nestjs
          imagePullPolicy: IfNotPresent
          env:
            - name: MS400_PORT
              valueFrom:
                secretKeyRef:
                  name: ms400-secret
                  key: MS400_PORT
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: ms400-secret
                  key: MONGODB_URI
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: ms400-secret
                  key: MONGODB_USER
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: ms400-secret
                  key: MONGODB_PASS
          ports:  
            - containerPort: 50100
---
apiVersion: v1
kind: Service
metadata:
  name: ms400-service
  namespace: ms400-namespace
spec:
  type: ClusterIP
  selector:
    app: ms400-pod
  ports:
    - protocol: TCP
      port: 50100
      targetPort: 50100